### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by itadventurer** [itadventurer/kafka-backup#2]
* [ ] [How it works](https://github.com/azapps/kafka-backup/blob/master/docs/How_it_works.md) #74
* [x] [Comparing Kafka Backup Solutions](https://github.com/azapps/kafka-backup/blob/master/docs/Comparing_Kafka_Backup_Solutions.md)
* [x] [Architecture](https://github.com/azapps/kafka-backup/blob/master/docs/Kafka_Backup_Architecture.md)
* [ ] [Tooling](https://github.com/azapps/kafka-backup/blob/master/docs/Tooling.md) #78
* [ ] Usage Guide #79
  * [ ] Reference Architecture
  * [ ] How to Backup
  * [ ] How to Restore
  * [ ] How to handle large backup sizes
  * [ ] How to do daily Backups
* [x] [Build and run](https://github.com/azapps/kafka-backup/blob/master/docs/Build_and_Run.md)
* [ ] [FAQ](https://github.com/azapps/kafka-backup/blob/master/docs/FAQ.md)
  * [x] #23 
  * [x] #32 
* [ ] ~Kafka Backup on Kubernetes~ RTFM nothing special about this
* [ ] How to restart the Kafka Backup: See [BackupSinkTask](https://github.com/itadventurer/kafka-backup/blob/master/src/main/java/de/azapps/kafkabackup/sink/BackupSinkTask.java#L82) #76
* [ ] Backup and Restore full Kafka Cluster including Zookeeper. Pointers: [system_test/backup_with_burry](https://github.com/itadventurer/kafka-backup/tree/master/system_test/backup_with_burry) #75

**Comment by prasus** [comment]
Eagerly waiting for the Kafka Backup on Kubernetes docs as I am planning to evaluate this on our k8s Kafka environment.

**Comment by itadventurer** [comment]
Waiting until Kafka 2.4 is released… For Kubernetes it is relatively straight-forward. Deploy kafka connect in standalone mode  with the kafka-backup jar as a K8s deployment

**Comment by jay7x** [comment]
Things I'd like to know:

1. How to reset offsets to make another cold backup?
1. What is backup strategy? Should I stop connector, move data to long-term storage, start it again? Or is it possible to do w/o stopping connector?
1. It's not clear for me about indices. I see how to recreate them though I'm not sure how to get partitions number e.g. (should I know it for every topic we have in our multi-tenant kafka?). Or can I just use max number of partitions we have?

Thank you!

**Comment by LBmaster001** [comment]
to 1:
`./bin/kafka-consumer-groups.sh --bootstrap-server=[server-ip]:[server-port] --command-config=./config/connect-standalone.properties --reset-offsets --to-earliest --group connect-backup-sink --all-topics --execute`
You can change `--all-topics` to `--topic [topic-name]`
You might want to change the groupname, but this should be the default one.
If you leave out the `--execute`, the command will only show you how the result will look like, but does not execute it !

**Comment by itadventurer** [comment]
Many things are now vastly simpler but still there are open points for documentation. I updated the initial Issue description to link to new issues for documentation. If you need more documentation please open a new ticket. I will close this issue.
