### ISSUE TITLE
Improve Test Coverage of Integration Tests

### ISSUE THREAD

**Issue by itadventurer** [itadventurer/kafka-backup#49]
* [ ] Support and differentiate between null and empty messages #14
* [x]  Restore can fail when at least one partition was empty #17 
* [ ] Starting the Backup Sink multiple times #41
* [ ] Delete old segments manually when doing a backup → should still work
